/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_JTest */

#ifndef _Included_com_example_hellojni_JTest
#define _Included_com_example_hellojni_JTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_JTest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hellojni_JTest_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
